export const skillsData = [
    "JavaScript",
    "TypeScript",
    "React",
    "Angular",
    "Next.js",
    "Tailwind CSS",
    "Node.js",
    "SCSS",
    "HTML",
    "CSS",
    "MySQL",
    "SQLite",
    "PostgreSQL",
    "Three.js",
    "Framer Motion",
    "C#",
    "Unity",
    "ASP.NET",
    "C/C++",
    "OpenGL",
    "Vulkan",
    "DirectX",
    "Docker",
    "Git",
]